### ISSUE TITLE
Combine efforts?

### ISSUE THREAD

**Issue by jonathantneal** [arpadHegedus/postcss-node-sass#1]
Hi @arpadHegedus,

I went to publish a similar module and saw your excellent work. Would you be interested in absorbing the work I’ve done?

https://github.com/jonathantneal/postcss-node-sass/#readme

Here are 3 key additions:

1. Support for passing Node Sass options via PostCSS Node Sass.
2. Preservation of source maps from Node Sass, as well as any PostCSS plugins run before it.
3. Feature tests, Node 4.x compatibility, automated tests for both Windows and *Nix environments.

**Comment by arpadHegedus** [comment]
Awesome. Thank you. I'll double check everything and will merge your code.

EDIT: I've checked your code and will merge some ideas and these features in the next couple of days. I hope this is all right with you. I don't want to simply merge your pull request as it completely overwrites my plugin and I want to keep it very, very simple.

**Comment by jonathantneal** [comment]
@arpadHegedus, thanks for checking this out! If there are ways to make it more simple, go for it. What kinds of things do you want simplified? Can I help? 😄 

What was important to me was not adding any options (just forwarding them from the plugin) and preserving source maps. Right now, my company is using things like postcss-import before node-sass, so losing all the file references was making debugging too rough, and sass does not respect imported sourcemaps ([reference](https://github.com/sass/node-sass/issues/2134)).

As for all the tests, it’s a quality requirement of PostCSS plugins (@ai could get into more detail), but it’s just good practice for any node module, as it also protects me against accidental breaking changes.

**Comment by jonathantneal** [comment]
@arpadHegedus, how goes the review?

**Comment by arpadHegedus** [comment]
I've merged some of your suggestions from #2 

Thank you, @jonathantneal
