### ISSUE TITLE
Compatibility with PostCSS 8

### ISSUE THREAD

**Issue by mtimofiiv** [arpadHegedus/postcss-node-sass#13]
The module does not work with PostCSS 8. There's quite some API changes since 7!

https://evilmartians.com/chronicles/postcss-8-plugin-migration

I'm not an expert at PostCSS plugins, so I'm not sure if to use `Once` or `AtRule` with this. I don't mind doing the work if someone can point me in the right direction.

**Comment by amprew** [comment]
@mtimofiiv  I created a PR here for upgrading to postcss 8 https://github.com/arpadHegedus/postcss-node-sass/pull/14

**Comment by arpadHegedus** [comment]
Resolved with #14

**Comment by amprew** [comment]
@arpadHegedus - what is the process in releasing to npm for this repo? Happy to help out
