### ISSUE TITLE
Release version 3.x.x to npm

### ISSUE THREAD

**Issue by andrewfc** [arpadHegedus/postcss-node-sass#17]
Hoping we can release version 3.x.x to npm with the changes that were introduced for postcss v8. Wondering if it is also worth keeping track of 3.0.0 and 3.1.0 so we have a release for both.

Not sure every commit needs a tag associated?

Thanks!

(@amprew - this is my account, raised under work account)

**Comment by FrankyFrankFrank** [comment]
I needed 3.x.x in a postcss v8 project I'm working on, so I installed it with the tar and it's working well.
Thanks everybody

**Comment by amprew** [comment]
@arpadHegedus thanks for making the git release, is there any update on publishing this release to npm too?

**Comment by arpadHegedus** [comment]
Added to npm
