### ISSUE TITLE
NPM Package does not support Node v18

### ISSUE THREAD

**Issue by jakefrancis** [arpadHegedus/postcss-node-sass#23]
The [node package](https://www.npmjs.com/package/postcss-node-sass) for this project does not support Node v18. 

There was a recent [PR merged ](https://github.com/arpadHegedus/postcss-node-sass/pull/22) that added support for Node v18 
I don't think the version number changed after merging the PR. As in it stayed at 3.1.2

It seems like the NPM package still has the old code in it `line 48` in `package.json.` 
https://www.npmjs.com/package/postcss-node-sass?activeTab=code

![Screenshot 2023-04-19 at 5 40 13 PM](https://user-images.githubusercontent.com/53124107/233206300-3f9b00c6-a2cd-467e-96f0-cf6f92b7630c.png)

Is there anyway we can update the package on NPM?

Thanks

**Comment by arpadHegedus** [comment]
I have republished it with a bumped version number. It now shows up properly in package.json.

Thanks for spotting it.
