### ISSUE TITLE
when sass.render return res.map is undefined catch error

### ISSUE THREAD

**Issue by winfredwyw** [arpadHegedus/postcss-node-sass#9]
`
return postcss.parse(res.css.toString(), {
    from: result.opts.from,
    map: {
          prev: JSON.parse(res.map.toString())  //  right here
    }
})
`

**Comment by arpadHegedus** [comment]
You need to log your res variable. Seems like these are not correct settings to parse. Please give full code example to investigate further.

**Comment by arpadHegedus** [comment]
I merged a pull request, please double check your issue if it still persists.
